all:
  hosts:
    inetRouter:
      ansible_host: 192.168.56.10
      bond_address: 192.168.255.1/30
    centralRouter:
      ansible_host: 192.168.56.11
      bond_address: 192.168.255.2/30
    officeRouter:
      ansible_host: 192.168.56.20
    testServer1:
      ansible_host: 192.168.56.21
      vlan: { id: 1, address: 10.10.10.1/24 }
    testClient1: 
      ansible_host: 192.168.56.22
      vlan: { id: 1, address: 10.10.10.254/24 }
    testServer2:
      ansible_host: 192.168.56.31
      vlan: { id: 2, address: 10.10.10.1/24 }
    testClient2:
      ansible_host: 192.168.56.32
      vlan: { id: 2, address: 10.10.10.254/24 }
